//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuerraIraqApp.VetWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VeteranoWS", Namespace="http://emilio.dev/")]
    [System.SerializableAttribute()]
    public partial class VeteranoWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        private System.DateTime FechaNacimientoField;
        
        private System.DateTime FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RangoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemotoLocalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Rango {
            get {
                return this.RangoField;
            }
            set {
                if ((object.ReferenceEquals(this.RangoField, value) != true)) {
                    this.RangoField = value;
                    this.RaisePropertyChanged("Rango");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string RemotoLocal {
            get {
                return this.RemotoLocalField;
            }
            set {
                if ((object.ReferenceEquals(this.RemotoLocalField, value) != true)) {
                    this.RemotoLocalField = value;
                    this.RaisePropertyChanged("RemotoLocal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://emilio.dev/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://emilio.dev/", ConfigurationName="VetWS.VetWebServiceSoap")]
    public interface VetWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://emilio.dev/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://emilio.dev/HelloWorld", ReplyAction="*")]
        GuerraIraqApp.VetWS.HelloWorldResponse HelloWorld(GuerraIraqApp.VetWS.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://emilio.dev/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<GuerraIraqApp.VetWS.HelloWorldResponse> HelloWorldAsync(GuerraIraqApp.VetWS.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://emilio.dev/Sumar", ReplyAction="*")]
        int Sumar(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://emilio.dev/Sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumarAsync(int a, int b);
        
        // CODEGEN: Generating message contract since element name veterano from namespace http://emilio.dev/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://emilio.dev/RegistrarVeterano", ReplyAction="*")]
        GuerraIraqApp.VetWS.RegistrarVeteranoResponse RegistrarVeterano(GuerraIraqApp.VetWS.RegistrarVeteranoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://emilio.dev/RegistrarVeterano", ReplyAction="*")]
        System.Threading.Tasks.Task<GuerraIraqApp.VetWS.RegistrarVeteranoResponse> RegistrarVeteranoAsync(GuerraIraqApp.VetWS.RegistrarVeteranoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://emilio.dev/", Order=0)]
        public GuerraIraqApp.VetWS.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(GuerraIraqApp.VetWS.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://emilio.dev/", Order=0)]
        public GuerraIraqApp.VetWS.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(GuerraIraqApp.VetWS.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://emilio.dev/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarVeteranoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarVeterano", Namespace="http://emilio.dev/", Order=0)]
        public GuerraIraqApp.VetWS.RegistrarVeteranoRequestBody Body;
        
        public RegistrarVeteranoRequest() {
        }
        
        public RegistrarVeteranoRequest(GuerraIraqApp.VetWS.RegistrarVeteranoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://emilio.dev/")]
    public partial class RegistrarVeteranoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GuerraIraqApp.VetWS.VeteranoWS veterano;
        
        public RegistrarVeteranoRequestBody() {
        }
        
        public RegistrarVeteranoRequestBody(GuerraIraqApp.VetWS.VeteranoWS veterano) {
            this.veterano = veterano;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarVeteranoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarVeteranoResponse", Namespace="http://emilio.dev/", Order=0)]
        public GuerraIraqApp.VetWS.RegistrarVeteranoResponseBody Body;
        
        public RegistrarVeteranoResponse() {
        }
        
        public RegistrarVeteranoResponse(GuerraIraqApp.VetWS.RegistrarVeteranoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://emilio.dev/")]
    public partial class RegistrarVeteranoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GuerraIraqApp.VetWS.Respuesta RegistrarVeteranoResult;
        
        public RegistrarVeteranoResponseBody() {
        }
        
        public RegistrarVeteranoResponseBody(GuerraIraqApp.VetWS.Respuesta RegistrarVeteranoResult) {
            this.RegistrarVeteranoResult = RegistrarVeteranoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VetWebServiceSoapChannel : GuerraIraqApp.VetWS.VetWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VetWebServiceSoapClient : System.ServiceModel.ClientBase<GuerraIraqApp.VetWS.VetWebServiceSoap>, GuerraIraqApp.VetWS.VetWebServiceSoap {
        
        public VetWebServiceSoapClient() {
        }
        
        public VetWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VetWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VetWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VetWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuerraIraqApp.VetWS.HelloWorldResponse GuerraIraqApp.VetWS.VetWebServiceSoap.HelloWorld(GuerraIraqApp.VetWS.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            GuerraIraqApp.VetWS.HelloWorldRequest inValue = new GuerraIraqApp.VetWS.HelloWorldRequest();
            inValue.Body = new GuerraIraqApp.VetWS.HelloWorldRequestBody();
            GuerraIraqApp.VetWS.HelloWorldResponse retVal = ((GuerraIraqApp.VetWS.VetWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuerraIraqApp.VetWS.HelloWorldResponse> GuerraIraqApp.VetWS.VetWebServiceSoap.HelloWorldAsync(GuerraIraqApp.VetWS.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuerraIraqApp.VetWS.HelloWorldResponse> HelloWorldAsync() {
            GuerraIraqApp.VetWS.HelloWorldRequest inValue = new GuerraIraqApp.VetWS.HelloWorldRequest();
            inValue.Body = new GuerraIraqApp.VetWS.HelloWorldRequestBody();
            return ((GuerraIraqApp.VetWS.VetWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Sumar(int a, int b) {
            return base.Channel.Sumar(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SumarAsync(int a, int b) {
            return base.Channel.SumarAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuerraIraqApp.VetWS.RegistrarVeteranoResponse GuerraIraqApp.VetWS.VetWebServiceSoap.RegistrarVeterano(GuerraIraqApp.VetWS.RegistrarVeteranoRequest request) {
            return base.Channel.RegistrarVeterano(request);
        }
        
        public GuerraIraqApp.VetWS.Respuesta RegistrarVeterano(GuerraIraqApp.VetWS.VeteranoWS veterano) {
            GuerraIraqApp.VetWS.RegistrarVeteranoRequest inValue = new GuerraIraqApp.VetWS.RegistrarVeteranoRequest();
            inValue.Body = new GuerraIraqApp.VetWS.RegistrarVeteranoRequestBody();
            inValue.Body.veterano = veterano;
            GuerraIraqApp.VetWS.RegistrarVeteranoResponse retVal = ((GuerraIraqApp.VetWS.VetWebServiceSoap)(this)).RegistrarVeterano(inValue);
            return retVal.Body.RegistrarVeteranoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuerraIraqApp.VetWS.RegistrarVeteranoResponse> GuerraIraqApp.VetWS.VetWebServiceSoap.RegistrarVeteranoAsync(GuerraIraqApp.VetWS.RegistrarVeteranoRequest request) {
            return base.Channel.RegistrarVeteranoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuerraIraqApp.VetWS.RegistrarVeteranoResponse> RegistrarVeteranoAsync(GuerraIraqApp.VetWS.VeteranoWS veterano) {
            GuerraIraqApp.VetWS.RegistrarVeteranoRequest inValue = new GuerraIraqApp.VetWS.RegistrarVeteranoRequest();
            inValue.Body = new GuerraIraqApp.VetWS.RegistrarVeteranoRequestBody();
            inValue.Body.veterano = veterano;
            return ((GuerraIraqApp.VetWS.VetWebServiceSoap)(this)).RegistrarVeteranoAsync(inValue);
        }
    }
}
