//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuerraIraqApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GuerraIraqAppDBEntities : DbContext
    {
        public GuerraIraqAppDBEntities()
            : base("name=GuerraIraqAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Veterano> Veterano { get; set; }
    
        public virtual int SPInsertVeterano(string cedula, string nombres, string apellidos, Nullable<System.DateTime> fechaNacimiento, string rango, string estado)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombresParameter = nombres != null ?
                new ObjectParameter("Nombres", nombres) :
                new ObjectParameter("Nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var rangoParameter = rango != null ?
                new ObjectParameter("Rango", rango) :
                new ObjectParameter("Rango", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPInsertVeterano", cedulaParameter, nombresParameter, apellidosParameter, fechaNacimientoParameter, rangoParameter, estadoParameter);
        }
    
        public virtual int SPUpdateRemoto(Nullable<int> id, string remotoLocal)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var remotoLocalParameter = remotoLocal != null ?
                new ObjectParameter("RemotoLocal", remotoLocal) :
                new ObjectParameter("RemotoLocal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPUpdateRemoto", idParameter, remotoLocalParameter);
        }
    }
}
